/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Alert } from '@mui/material';
import { styled } from '@mui/material/styles';

 
const AlertFilled1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const AlertFilled2 = styled(Alert)({  
  width: `320px`,  
  margin: `0px`,  
});
 
function AlertFilled(props) {
  return (
    <AlertFilled1 className={props.className} >
      <AlertFilled2 variant="filled" severity={"error"}   > Description </AlertFilled2>
    </AlertFilled1>
  );
}

export default AlertFilled;
