/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Alert, Button } from '@mui/material';
import { styled } from '@mui/material/styles';
import Avatar1 from 'components/Avatar1/Avatar1';
import Switch1 from 'components/Switch1/Switch1';
import Radio1 from 'components/Radio1/Radio1';
import Checkbox1 from 'components/Checkbox1/Checkbox1';
import Link1 from 'components/Link1/Link1';
import Icon1 from 'components/Icon1/Icon1';
import Autocomplete1 from 'components/Autocomplete1/Autocomplete1';
import useSuperContainer from 'components/SuperContainer/useSuperContainer';
 
const SuperContainer1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `1px 24px`,  
  boxSizing: `border-box`,  
  height: "100%",  
  width: "100%",  
});
  
const Frame12 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `26px 24px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Avatar2 = styled(Avatar1)(({ theme }) =>({  
  margin: `0px`,  
}));
  
const Switch2 = styled(Switch1)(({ theme }) =>({  
  margin: `0px 0px 0px 10px`,  
}));
  
const Frame9 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `17px 30px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 13px`,  
});
  
const Radio2 = styled(Radio1)(({ theme }) =>({  
  margin: `0px`,  
}));
  
const Radio3 = styled(Radio1)(({ theme }) =>({  
  margin: `29px 0px 0px 0px`,  
}));
  
const Frame10 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `10px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 13px`,  
});
  
const Checkbox2 = styled(Checkbox1)(({ theme }) =>({  
  margin: `0px`,  
}));
  
const Checkbox3 = styled(Checkbox1)(({ theme }) =>({  
  margin: `10px 0px 0px 0px`,  
}));
  
const Checkbox4 = styled(Checkbox1)(({ theme }) =>({  
  margin: `10px 0px 0px 0px`,  
}));
  
const Frame11 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `26px 35px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 13px`,  
});
  
const Link2 = styled(Link1)(({ theme }) =>({  
  margin: `0px`,  
}));
  
const Icon2 = styled(Icon1)(({ theme }) =>({  
  margin: `15px 0px 0px 0px`,  
}));
  
const Avatar3 = styled(Avatar1)(({ theme }) =>({  
  margin: `15px 0px 0px 0px`,  
}));
  
const AlertFilled = styled(Alert)({  
  width: `320px`,  
  margin: `15px 0px 0px 0px`,  
});
  
const Switch3 = styled(Switch1)(({ theme }) =>({  
  margin: `15px 0px 0px 0px`,  
}));
  
const ButtonContained = styled(Button)({  
  margin: `15px 0px 0px 0px`,  
});
  
const Autocomplete2 = styled(Autocomplete1)(({ theme }) =>({  
  margin: `15px 0px 0px 0px`,  
}));
 
function SuperContainer(props) {
  const {fns} = useSuperContainer();
  return (
    <SuperContainer1 className={props.className} >
      <Frame12 >
        <Avatar2   />
        <Switch2   />
      </Frame12>
      <Frame9 >
        <Radio2   />
        <Radio3   />
      </Frame9>
      <Frame10 >
        <Checkbox2   />
        <Checkbox3   />
        <Checkbox4   />
      </Frame10>
      <Frame11 >
        <Link2   />
        <Icon2   />
        <Avatar3   />
        <AlertFilled variant="filled" severity={"error"}   > Description </AlertFilled>
        <Switch3   />
        <ButtonContained variant="contained" size="large" color="info"  onClick={fns.handleOnClick}  > Large </ButtonContained>
        <Autocomplete2   />
      </Frame11>
    </SuperContainer1>
  );
}

export default SuperContainer;
