/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Switch, FormControlLabel } from '@mui/material';
import { styled } from '@mui/material/styles';

 
const Switch2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const FormControlLabel1 = styled(FormControlLabel)({  
  margin: `0px`,  
});
 
function Switch1(props) {
  return (
    <Switch2 className={props.className} >
      <FormControlLabel1 control={<Switch defaultChecked={true} color="info" size="medium" />} />
    </Switch2>
  );
}

export default Switch1;
